db.url=jdbc:mysql://shuttle.proxy.rlwy.net:57535/railway?serverTimezone=Asia/Ho_Chi_Minh&sessionVariables=time_zone='%2B07:00'&useSSL=false&allowPublicKeyRetrieval=true
db.user=root
db.password=DcIOOXozRTjcCpofPFhcBsKSAyxJAHGC

mail.user=kduongnguyen07@gmail.com
mail.password=qgus rhhk nyuv vgte